# .github/workflows/ci.yml
name: CI - Lint, Build & Publish Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint (single job to avoid flake8 multiprocessing issues)
        run: |
          pip install flake8
          flake8 --jobs=1 --config=.flake8 src app.py

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-capstone:latest
          platforms: linux/amd64

      - name: Verify image pushed (list tags)
        run: echo "Image pushed by ${ { secrets.DOCKERHUB_USERNAME } }"
